### PR TITLE
Fixed detect script

### LINKED ISSUE #1: Push rejected, failed to detect set buildpack
I have tried to setup your buildpack (using Heroku new support for multiple buildpacks https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app) but my build failed with following error message:

```
-----> Fetching set buildpack https://github.com/Lostmyname/heroku-post-build-clean-buildpack... done
 !     Push rejected, failed to detect set buildpack https://github.com/Lostmyname/heroku-post-build-clean-buildpack
```

Any idea how to fix this problem?

### PR DESCRIPTION
**Pull request by moravcik**
Fixed #1, added `echo "POST BUILD CLEAN"` and `exit 0` to detect script

### CODE REVIEW

**Comment by mcmillan** [comment]
Hi @moravcik! Thanks for the PR. Can you squash your commits and we'll get this merged?

**Comment by moravcik** [comment]
Hi @mcmillan, it took me a while to find out how to do the squash of commits, but it seems it is done now.

**Comment by rvetere** [comment]
please merge this 👍

**Review by nruth — APPROVED** [review]
Installation fails without this change.

**Comment by davidguthu** [comment]
Why hasn't this been merged?

**Comment by moravcik** [comment]
You can use my fork, if you like
https://github.com/moravcik/heroku-buildpack-post-build-clean

**Comment by mcmillan** [comment]
Sorry for the delay in getting this merged, folks!

**Pull request merged**
